spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    username: 'postgres'
    password: 'JIT..waveMode'
    url: 'jdbc:postgresql://localhost:5433/blogdb?useUnicode=true&characterEncoding=utf8;DB_CLOSE_DELAY=-1'
    driver-class-name: org.postgresql.Driver

server:
  port: 8080
  servlet:
    context-path: '/simpleblog'