CREATE TABLE IF NOT EXISTS blog_user
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT users_pkey
            PRIMARY KEY ,
    email    VARCHAR(255),
    lastname VARCHAR(255) NOT NULL,
    name     VARCHAR(255) NOT NULL,
    password VARCHAR(255),
    role     VARCHAR(255)
);